### ISSUE TITLE
ユーザー情報のページが寂しい

### ISSUE THREAD

**Issue by g-fujioka** [g-fujioka/daily_report#37]
メールアドレスと部署名しか情報がないので、自分が作成した日報の一覧も表示するようにする。
また、コメントが付いているかどうか分からないので、コメント数も表示する。

**Comment by kazuhisa** [comment]
* リスト表示のViewはreportsの明細と共有できそうなのでpartialで切り出そう
* コメント数はbootstrapのBadgeを使うとかっこいいかも
